language: generic
sudo: required
services:
  - docker

before_install:
  #  at the ned we dom't use . but ./client --> the ast parameter is a context, so our context is client directory
  - docker build -t mateusz86pl2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mateusz86pl2/react-test npm test

after_success:
  - docker build -t mateusz86pl2/multi-client ./client
  - docker build -t mateusz86pl2/multi-nginx ./nginx
  - docker build -t mateusz86pl2/multi-server ./server
  - docker build -t mateusz86pl2/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mateusz86pl2/multi-client
  - docker push mateusz86pl2/multi-nginx
  - docker push mateusz86pl2/multi-server
  - docker push mateusz86pl2/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-176901363719
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
